import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/providers";
import NavBar from "./components/NavBar";
import { Box } from "@chakra-ui/react";
import ErrorAlert from "./components/ErrorAlert";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          <ErrorAlert />
          <Box padding={5}>
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}
